name = "serverless-qrcode-hub"
main = "index.js"
compatibility_date = "2025-03-10"

[[d1_databases]]
binding = "DB"
database_name = "qrcode_hub"
# 注意：将下面的 id 替换为你自己拷贝的 D1 存储的 id 才能正常使用！
database_id = "0f3a6ea4-633f-4c06-92cc-651b1a442905"

[triggers]
crons = ["0 2 */1 * *"]

[[env.dev.d1_databases]]
binding = "DB"
database_name = "qrcode_hub_dev"
database_id = "1cfa1ef6-a076-410b-aa19-50f63411313c"
PASSWORD="demo"

[env.dev.triggers]
crons = ["*/10 * * * * *"]

[env.dev.vars]
PASSWORD = "demo" # 在这里设置你的

[assets]
directory = "./dist"
binding = "ASSETS"
